export const REPLACE_PROVIDERS = 'REPLACE_PROVIDERS';
export const FETCH_STORE_PROVIDERS = 'FETCH_STORE_PROVIDERS';
export const FETCH_MANY_STORE_PROVIDERS = 'FETCH_MANY_STORE_PROVIDERS';
export const FETCH_STORES = 'FETCH_STORES';
export const REPLACE_STORES = 'REPLACE_STORES';

export const REPLACE_STORE_PROVIDERS = 'REPLACE_STORE_PROVIDERS';
export const REPLACE_MANY_STORE_PROVIDERS = 'REPLACE_MANY_STORE_PROVIDERS';
