export const INIT_MODEL = 'INIT_MODEL';
export const MODEL_REMOVE_PRODUCT = 'MODEL_REMOVE_PRODUCT';
export const MODEL_ADD_PRODUCT = 'MODEL_ADD_PRODUCT';
export const MODEL_ADD_RAW_PRODUCT = 'MODEL_ADD_RAW_PRODUCT';
export const MODEL_UPDATE_PRODUCT_QUANTITY = 'MODEL_UPDATE_PRODUCT_QUANTITY';
export const MODEL_UPDATE_PRODUCT_STORE_LOCATION = 'MODEL_UPDATE_PRODUCT_STORE_LOCATION';
export const MODEL_UPDATE_PRODUCT_LOT_ID = 'MODEL_UPDATE_PRODUCT_LOT_ID';
export const MODEL_UPDATE_STORE_ID = 'MODEL_UPDATE_STORE_ID';
export const MODEL_UPDATE_WAREHOUSE_ID = 'MODEL_UPDATE_WAREHOUSE_ID';
export const MODEL_UPDATE_PROVIDER_ID = 'MODEL_UPDATE_PROVIDER_ID';
export const MODEL_UPDATE_TYPE = 'MODEL_UPDATE_TYPE';
export const MODEL_UPDATE_NOTE = 'MODEL_UPDATE_NOTE';
export const UPDATE_LOADING_DIALOG = 'UPDATE_LOADING_DIALOG';
export const UPDATE_ERROR_DIALOG = 'UPDATE_ERROR_DIALOG';
export const UPDATE_STORE_ID = 'UPDATE_STORE_ID';

export const ADD_LOADING_MESSAGE = 'REMOVE_LOADING_MESSAGE';
export const REMOVE_LOADING_MESSAGE = 'REMOVE_LOADING_MESSAGE';

export const ADD_ERROR_MESSAGE = 'REMOVE_ERROR_MESSAGE';
export const REMOVE_ERROR_MESSAGE = 'REMOVE_ERROR_MESSAGE';
