export const UPDATE_STORE = 'UPDATE_STORE';
export const UPDATE_MODEL = 'UPDATE_MODEL';
export const UPDATE_MODEL_SELL = 'UPDATE_MODEL_SELL';
export const UPDATE_MODEL_INTERNAL = 'UPDATE_MODEL_INTERNAL';
