export const GET_FILTER = 'GET_FILTER';
export const GET_INVOICES = 'GET_INVOICES';

export const INVOICE_IDS_SHOWING = 'INVOICE_IDS_SHOWING';
export const INVOICE_IDS_SELECTED = 'INVOICE_IDS_SELECTED';
